name: Continuous Integration

on:
  push:
   branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: echo version
        run: dotnet --version

      - name: restore dependencies
        run: dotnet restore

      - name: build app
        run: dotnet build -c Release --no-restore
